### ISSUE TITLE
Orange border appears on clicking of any item from the topmost navbar

### ISSUE THREAD

**Issue by ritikasource** [italia/developers.italia.it#495] opened 2020-02-01 16:15 UTC
If any item from the topmost navbar is selected then along with a white underline there's this orange border that appears along with it. This border is also dysfunctional when the site is reloaded or refreshed.

**Comment by libremente** [comment] 2020-02-01 16:49
Hi @ritikasource and thanks for your issue! This sound like a weird behaviour and I'd like to dig a bit deeper in it. Could you please provide some more information regarding your discovery in order to make it reproducible? Something like your specs (e.g., browser used) or also a picture representing the issue could be really useful here. 
Thanks!

**Comment by ritikasource** [comment] 2020-02-01 17:12
Hey @libremente, I am using chrome as browser and as far as this issue is concerned as I said it's dysfunctional I am unable to retrace this effect on the navbar right now but this same issue can be seen at the 'menu' section.
Here's the screenshot for the same:
![image](https://user-images.githubusercontent.com/54948869/73595963-f728e800-4543-11ea-8987-9a40ea883f8a.png)

**Comment by libremente** [comment] 2020-02-03 09:17
Thank you @ritikasource.
However, this repo is dedicated to the https://developers.italia.it website and not the SPID one. I don't know where that repo is, I can check it out.

**Comment by libremente** [comment] 2020-02-03 11:10
Actually @ritikasource I was able to reproduce such a behaviour after clicking rapidly many times on the links also in Developers Italia. I need to investigate further on this

**Comment by ritikasource** [comment] 2020-02-03 14:53
@libremente, Initially I found this issue in the Developers Italia navbar later on when I traversed in the attached links, those too showed the same issue.

**Comment by libremente** [comment] 2020-02-03 16:56
Ok, it looks like the behaviour is correct on Chrome (orange boxes allow to navigate the page by hitting tab and using just the keyboard) whilst on Firefox we have a strange behaviour. We need to dig further on this. Do you have a suggestion?

**Comment by ritikasource** [comment] 2020-02-03 17:14
Actually,@libremente I am myself digging at the issue as soon as I get a hold of it I'll get back at you.

**Comment by libremente** [comment] 2020-05-22 17:15
Newer versions of Firefox work as expected, showing orange boxes that allow to navigate using the tab. I am closing this issue for this reason, please let me know if it is still showing up. Thank you!

**Closed by libremente** 2020-05-22 17:15 UTC
Labels: frontend, help wanted, triage
